# Generated by Django 5.2.4 on 2025-07-12 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=7, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo', models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor')], default='estudiante', max_length=15)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('creditos', models.IntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=15)),
                ('estudiantes', models.ManyToManyField(limit_choices_to={'tipo': 'estudiante'}, related_name='materia_cursada', to='tareas.persona')),
                ('profesor', models.ForeignKey(limit_choices_to={'tipo': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='materia_impartida', to='tareas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('puntaje', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('estudiante', models.ForeignKey(limit_choices_to={'tipo': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='tarea_asignada', to='tareas.persona')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.materia')),
                ('profesor', models.ForeignKey(limit_choices_to={'tipo': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='revisa_tarea', to='tareas.persona')),
            ],
        ),
    ]
